# Copyright (c) 2012-2017 Sebastien Rombauts (sebastien.rombauts@gmail.com)

# Run on the default infrastructure, which is Container Based Ubuntu 14.04
#sudo: false

cache:
  apt: true

language: cpp

compiler:
  - clang
  - gcc

# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake ..

# build examples, and run tests (ie make & make test)
script:
  - cmake --build .
