# Copyright (c) 2012-2017 Sebastien Rombauts (sebastien.rombauts@gmail.com)

# build format
version: "{build}"

os: Visual Studio 2017
platform:
  - x64

environment:
  VULKAN_SDK: "C:\\VulkanSDK\\1.0.65.0\\"

# scripts that run after cloning repository
install:
  - git submodule update --init --recursive
  - curl --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.0.65.0/windows/VulkanSDK-1.0.65.0-Installer.exe
  - VulkanSDK.exe /S

# scripts to run before build
before_build:
  - mkdir build
  - cd build
  - cmake ..

# build example in default Debug configuration
build_script:
  - cmake --build .

after_build:
  - cd build\Debug
  - 7z a VulkanTutorialDebug.zip VulkanTutorial.exe shaders\*

artifacts:
  - path: build\Debug\VulkanTutorialDebug.zip
    name: VulkanTutorialDebug
