# Copyright (c) 2012-2017 Sebastien Rombauts (sebastien.rombauts@gmail.com)

# build format
version: "{build}"

# scripts that run after cloning repository
install:
 - git submodule update --init --recursive

# scripts to run before build
before_build:
  - mkdir build
  - cd build
  - cmake ..

# build example
build_script:
  - cmake --build .
